name: CI
on:
  - push

jobs:
  test-on-windows:
    runs-on: windows-latest
    env:
      CACHE_NUM: 0
    steps:
      # TODO: figure this out, add caching to all steps
      # - uses: actions/cache@v1
      #   with:
      #     path: C:\Temp\Choco
      #     key: ${{ env.CACHE_NUM }}
      # - uses: crazy-max/ghaction-chocolatey@v1
      #   with:
      #     args: config set cacheLocation C:\Temp\Choco
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install emacs
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: latest
      - name: create conda environment foo
        run: conda create -y -n foo python=3.6
      - uses: actions/checkout@v1
      - name: install dependencies & run tests
        run: >-
          emacs -Q --batch -L .
          --load "ci/deps.el"
          --load "conda.el"
          --load "test/conda-test.el"
          -f ert-run-tests-batch-and-exit

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        emacs_version:
          - 25.3
          - 26.3
          - 27.1
          - 28.1
          - snapshot
        miniconda_version:
          # - 4.4.10
          # - 4.5.12
          - 4.6.14
          - 4.7.12
          - 4.8.4
          - 4.12.0
          - 4.13.0
          - latest
    # TODO: specify conda envs in an env var or something
    # env:
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: ${{ matrix.miniconda_version }}
      - name: create conda environment foo
        run: conda create -y -n foo python=3.6
      - uses: actions/checkout@v1
      - name: install dependencies & run tests
        run: >-
          emacs -Q --batch -L .
          --load "ci/deps.el"
          --load "conda.el"
          --load "test/conda-test.el"
          -f ert-run-tests-batch-and-exit
